DATA SEGMENT BCD DW 7865H
TEMP DW 4 DUP(?) HEX DW ?
DATA ENDS

CODE SEGMENT
ASSUME CS: CODE, DS: DATA START:
MOV AX, DATA MOV DS, AX

MOV BX, BCD MOV SI, 0
MOV CL, 04

GET_EACH_DIGIT:;GETTING EACH INDIVIDUAL DIGIT AND STORING IN TEMP MOV AX, BX
AND AX, 0FH
MOV TEMP[SI], AX INC SI
INC SI
SHR BX, CL CMP BX, 0
JNZ GET_EACH_DIGIT

LEA SI, TEMP MOV BX, [SI] MOV DI, 03H MOV CX, 0AH

;MULTIPLYING EACH INDIVIDUAL DIGIT BY 1, 0AH, 0AH^2 AND 0AH^3 MULTIPLY_AND_ADD_DIGITS:
INC SI INC SI
MOV AX, [SI] MUL CX ADD BX, AX
MOV AX, 0AH MUL CX
MOV CX, AX DEC DI
JNZ MULTIPLY_AND_ADD_DIGITS
 
MOV HEX, BX

MOV AH, 4CH INT 21H
CODE ENDS END START
