DATA SEGMENT HEX DB 0B8H
TEMP DB 3 DUP(0) BCD DW ?
DATA ENDS

CODE SEGMENT
ASSUME CS:CODE, DS: DATA START:
MOV AX, DATA MOV DS, AX

MOV AL, HEX MOV CL, 0AH LEA SI, TEMP

REPEAT_DIV:;REPEATEDLY DEVIDE THE NUMBER BY 0AH MOV AH, 0
DIV CL MOV[SI], AH INC SI
CMP AL, 0
JNZ REPEAT_DIV

LEA SI, TEMP MOV CL, 04 MOV AL, [SI+1] ROR AL, CL ADD AL, [SI] MOV AH, [SI+2] MOV BCD, AX MOV AH, 4CH INT 21H
CODE ENDS END START
