DATA SEGMENT
	    X DD 22099720H
	    Y DD 88745474H
	    RES DD ?
	    CARRY DB ?
	DATA ENDS
	

	CODE SEGMENT
	    ASSUME CS: CODE, DS: DATA
	START:
	    MOV AX, DATA
	    MOV DS, AX
	

	    MOV AX, WORD PTR X
	    MOV BX, WORD PTR Y
	    ADD AX, BX
	    MOV WORD PTR RES, AX
	    MOV AX, WORD PTR X+2
	    MOV BX, WORD PTR Y+2
	    ADC AX, BX
	    MOV WORD PTR RES+2, AX
	    ADC CARRY, 0
	

	    MOV AH, 4CH
	    INT 21H
	CODE ENDS
	END START
