DATA SEGMENT
	    X DQ 9876543298765432H
	    Y DQ 1234567812345678H
	    RES DQ ?
	    CARRY DB ?
	DATA ENDS
	

	CODE SEGMENT
	    ASSUME CS: CODE, DS: DATA
	START:
	    MOV AX, DATA
	    MOV DS, AX
	

	    MOV AX, WORD PTR X
	    MOV BX, WORD PTR Y
	    ADD AX, BX
	    MOV WORD PTR RES, AX
	

	    MOV AX, WORD PTR X+2
	    MOV BX, WORD PTR Y+2
	    ADC AX, BX
	    MOV WORD PTR RES+2, AX
	

	    MOV AX, WORD PTR X+4
	    MOV BX, WORD PTR Y+4
	    ADC AX, BX
	    MOV WORD PTR RES+4, AX
	

	    MOV AX, WORD PTR X+6
	    MOV BX, WORD PTR Y+6
	    ADC AX, BX
	    MOV WORD PTR RES+6, AX
	

	    ADC CARRY, 0
	

	    MOV AH, 4CH
	    INT 21H
	CODE ENDS
	END START
